// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Path is relative to the `prisma/` folder, so use ./dev.db (not ./prisma/dev.db)
    url: "file:./dev.db",
  },
});

